# Site settings
description: A blog written by a 10th grade kid
baseurl: "/myblog/" # the subpath of your site, e.g. /blog/
url: "http://rocka0.github.io/myblog" # the base hostname & protocol for your site

# User settings
username: Tushar Chenan
user_description: Front + Back end Developer
user_title: Rocka0
email: tusky2002@gmail.com
twitter_username:
github_username: rocka0
gplus_username:  Tush_Chen
disqus_username: rocka0

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
